init commit
11Nastiv/Sushishopbot pull request #1
Opened 2023-05-14 14:22 UTC by 11Nastiv

Бот для Сушикафе  с модульной системой (заказ, просмотр меню, редактирование админом меню удаленно)

2023-05-15 08:17 UTC, sergei-prokhorov-igorevich commented
Перенести все кроме (requirements.txt и .gitignore) в каталог src

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on sushi_bot.py
> +    print('Бот вышел в онлайн')
Правильнее сказать 'вошёл в онлайн'.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on sushi_bot.py
> +async def on_startup(_):
А для чего указан не используемый аргумент _ в функции?

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on to_json.py
> +import json
Вынести файл в новый каталог src/utils.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on to_json.py
> +with open('cenz.txt', encoding='utf-8') as r:
Вынести 'cenz.txt' в константу и разместить в начале этого скрипта.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on keyboards/client_kb.py
> +#b4 = KeyboardButton('Поделиться номером',request_contact=True)
Закомментированный код не принято оставлять в develop/main ветке. Можно либо удалить, либо перенести себе в какую-нибудь локальную ветку.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on keyboards/client_kb.py
> +kb_client.add(b1).add(b2).add(b3)#.row(b4,b5)
Тоже закомменченный код.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on handlers/other.py
> +    if {i.lower().translate(str.maketrans('', '', string.punctuation)) for i in message.text.split(' ')}\
Необходимо разделить эту длинную строку на отдельные переменные, что бы длины строк были не больше 60 символов.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on handlers/admin.py
> +
Не должно быть пропусков больше, чем 1 строка. Проверь пожалуйста по всем проектам.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on handlers/admin.py
> +        await message.reply('Теперь введи название')
Все введи заменить на введите

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on handlers/admin.py
> +    await bot.send_message(message.from_user.id, 'Чего изволите?', reply_markup=admin_kb.button_case_admin)
Лучше переписать текстовки с неформального языка на формальный. "Желаете оформить заказ?" и тд.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +import sqlite3 as sq
Переименовать каталог "data_base" в "db".

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +    if base:
Здесь отсутствует блок else. Что если не удалось подключиться к БД?!

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +    base.execute('CREATE TABLE IF NOT EXISTS menu(img TEXT, name TEXT PRIMARY KEY, description TEXT, price TEXT)')
Все sql-запросы переписать из uppercase в lowercase.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +    for ret in cur.execute('SELECT * FROM menu').fetchall():
Использование asterisk-символа в sql - bad practic. Необходимо переписать на конкретные поля таблицы.

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +    return cur.execute('SELECT * FROM menu').fetchall()
asterisk-символ

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +    cur.execute('DELETE FROM menu WHERE name == ?', (data,))
Лишняя запятая?!

2023-05-15 11:22 UTC, sergei-prokhorov-igorevich commented on data_base/sqlite_db.py
> +        await bot.send_photo(message.from_user.id, ret[0], f'{ret[1]}\nОписание: {ret[2]}\nЦена {ret[-1]}')
Слой Базы данных не должен уметь дописывать информацию к данным, в данном случае "\nОписание:". Он должен лишь отвечать за запись, считывание из БД.

2023-05-17 13:55 UTC, 11Nastiv commented on sushi_bot.py
> +    print('Бот вышел в онлайн')
Исправлено.

2023-05-17 13:56 UTC, 11Nastiv commented on sushi_bot.py
> +async def on_startup(_):
Убрала

2023-05-17 13:56 UTC, 11Nastiv commented on to_json.py
> +import json
Вынесла.

2023-05-17 13:56 UTC, 11Nastiv commented on to_json.py
> +with open('cenz.txt', encoding='utf-8') as r:
Поправила.

2023-05-17 13:56 UTC, 11Nastiv commented on keyboards/client_kb.py
> +#b4 = KeyboardButton('Поделиться номером',request_contact=True)
Сделано!

2023-05-17 13:56 UTC, 11Nastiv commented on data_base/sqlite_db.py
> +    base.execute('CREATE TABLE IF NOT EXISTS menu(img TEXT, name TEXT PRIMARY KEY, description TEXT, price TEXT)')
Сделано!

2023-05-17 13:56 UTC, 11Nastiv commented on data_base/sqlite_db.py
> +    for ret in cur.execute('SELECT * FROM menu').fetchall():
Сделано!

2023-05-17 13:57 UTC, 11Nastiv commented on data_base/sqlite_db.py
> +    return cur.execute('SELECT * FROM menu').fetchall()
Поправила.

2023-05-17 13:57 UTC, 11Nastiv commented on data_base/sqlite_db.py
> +    cur.execute('DELETE FROM menu WHERE name == ?', (data,))
Да, убрала.

2023-05-17 13:58 UTC, 11Nastiv commented on data_base/sqlite_db.py
> +        await bot.send_photo(message.from_user.id, ret[0], f'{ret[1]}\nОписание: {ret[2]}\nЦена {ret[-1]}')
Обсудили. Позже доделаю.

2023-05-18 10:24 UTC, sergei-prokhorov-igorevich requested changes

2023-05-18 10:24 UTC, sergei-prokhorov-igorevich commented on src/utils/to_json.py
> +#file = 'cenz.txt'
Остался коммент

2023-05-18 10:24 UTC, sergei-prokhorov-igorevich commented on src/handlers/admin.py
> +
Остались пустые строки

2023-05-20 04:54 UTC, sergei-prokhorov-igorevich commented on src/handlers/admin.py
> +
Не исправлено

2023-05-20 09:52 UTC, sergei-prokhorov-igorevich commented
Замечаний нет, ПР можно вливать в мейн.

2023-05-21 01:07 UTC, merged